drop table METAL.ITEMS;
drop table METAL.BANDS;
drop table METAL.LABELS;
drop table METAL.CATEGORIES;
drop table METAL.COUNTRIES;
drop table METAL.GENRES;
drop table METAL.IMAGES;
drop table METAL.USERS;
drop table METAL.ROLES;

create table METAL.BANDS (ID integer primary key, NAME varchar(100), WEBSITE varchar(500), LABEL_ID integer, COUNTRY_ID integer, IMAGE_ID integer);
create table METAL.CATEGORIES(ID integer primary key, NAME varchar(100));
create table METAL.COUNTRIES(ID integer primary key, NAME varchar(100));
create table METAL.GENRES(ID integer primary key, NAME varchar(100));
create table METAL.IMAGES(ID integer primary key, NAME varchar(100));
create table METAL.ITEMS(ID integer primary key, NAME varchar(100), PRICE double, STOCK integer, CATEGORY_ID integer, IMAGE_ID integer, BAND_ID integer, GENRE_ID integer, LABEL_ID integer);
create table METAL.LABELS (ID integer primary key, NAME varchar(100), WEBSITE varchar(500), COUNTRY_ID integer, IMAGE_ID integer);
create table METAL.ROLES(ID  integer primary key, NAME varchar(100));
create table METAL.USERS(ID  integer primary key, USERNAME varchar(100), PASSWORD varchar(25), ROLE_ID integer);

ALTER TABLE METAL.BANDS ADD FOREIGN KEY (LABEL_ID) REFERENCES METAL.LABELS (ID);
ALTER TABLE METAL.BANDS ADD FOREIGN KEY (COUNTRY_ID) REFERENCES METAL.COUNTRIES (ID);
ALTER TABLE METAL.BANDS ADD FOREIGN KEY (IMAGE_ID) REFERENCES METAL.IMAGES (ID);
ALTER TABLE METAL.ITEMS ADD FOREIGN KEY (CATEGORY_ID) REFERENCES METAL.CATEGORIES (ID);
ALTER TABLE METAL.ITEMS ADD FOREIGN KEY (IMAGE_ID) REFERENCES METAL.IMAGES (ID);
ALTER TABLE METAL.ITEMS ADD FOREIGN KEY (BAND_ID) REFERENCES METAL.BANDS (ID);
ALTER TABLE METAL.ITEMS ADD FOREIGN KEY (GENRE_ID) REFERENCES METAL.GENRES (ID);
ALTER TABLE METAL.ITEMS ADD FOREIGN KEY (LABEL_ID) REFERENCES METAL.LABELS (ID);
ALTER TABLE METAL.LABELS ADD FOREIGN KEY (COUNTRY_ID) REFERENCES METAL.COUNTRIES (ID);
ALTER TABLE METAL.LABELS ADD FOREIGN KEY (IMAGE_ID) REFERENCES METAL.IMAGES (ID);
ALTER TABLE METAL.USERS ADD FOREIGN KEY (ROLE_ID) REFERENCES METAL.ROLES (ID);

INSERT INTO METAL.ROLES (ID, "NAME") 
	VALUES (1, 'user');
INSERT INTO METAL.ROLES (ID, "NAME") 
	VALUES (2, 'admin');

INSERT INTO METAL.USERS (ID, USERNAME, PASSWORD, ROLE_ID) 
	VALUES (1, 'user', 'user', 1);
INSERT INTO METAL.USERS (ID, USERNAME, PASSWORD, ROLE_ID) 
	VALUES (2, 'admin', 'admin', 2);
